# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_greetings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequingAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Greetings',
        ),
    ]
