# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20160206_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequingaccount',
            name='name',
            field=models.CharField(default=b'main', max_length=60),
        ),
    ]
