# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_chequingaccount_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
                ('goal', models.FloatField(default=0)),
                ('name', models.CharField(default=b'main', max_length=60)),
            ],
        ),
    ]
